<a href="https://colab.research.google.com/github/PlanetDestroyyer/Pytorch-Tutorial/blob/main/01_Pytorch_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch

In [4]:
t1 = torch.tensor(1)

In [5]:
t1

tensor(1)

In [6]:
t2 = torch.tensor(4.)

In [7]:
t2

tensor(4.)

In [8]:
t3 = torch.tensor([1,2,3])

In [9]:
t3

tensor([1, 2, 3])

In [10]:
t3.dtype

torch.int64

In [11]:
t4 = torch.tensor([1,2,3,4,5],dtype=torch.int16)
t4

tensor([1, 2, 3, 4, 5], dtype=torch.int16)

In [12]:
t4.dtype

torch.int16

In [13]:
t5 = torch.tensor([[1,2,3],[4,5,6]])
t5

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
t6 = torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
t6

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [15]:
t1
t1.shape

torch.Size([])

In [16]:
t2.shape

torch.Size([])

In [17]:
t3.shape

torch.Size([3])

In [18]:
t4.shape

torch.Size([5])

In [19]:
t5.shape

torch.Size([2, 3])

In [20]:
t6.shape

torch.Size([2, 2, 3])

In [21]:
x = torch.tensor(3.)
w = torch.tensor(4.,requires_grad=True)
b = torch.tensor(5.,requires_grad=True)
x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [22]:
y = w*x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [23]:
y.backward()

In [24]:
print('dy/dx:',x.grad)
print('dy/dw:',w.grad)
print('dy/db:',b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


In [25]:
t7 = torch.full((3,2),42)
t7

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [26]:
t8 = torch.full((3,2),4,dtype=torch.float32)
t8

tensor([[4., 4.],
        [4., 4.],
        [4., 4.]])

In [27]:
t9 = torch.cat((t7,t8))

In [28]:
t9

tensor([[42., 42.],
        [42., 42.],
        [42., 42.],
        [ 4.,  4.],
        [ 4.,  4.],
        [ 4.,  4.]])

In [29]:
t9 = torch.sin(t7)

In [30]:
t9

tensor([[-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [31]:
import numpy as np
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [32]:
y = torch.from_numpy(x)

In [33]:
y

tensor([[1, 2],
        [3, 4]])

In [34]:
x.dtype,y.dtype

(dtype('int64'), torch.int64)

In [35]:
z = y.numpy()

In [36]:
z

array([[1, 2],
       [3, 4]])

In [37]:
z.dtype

dtype('int64')