<a href="https://colab.research.google.com/github/PlanetDestroyyer/Pytorch-Tutorial/blob/main/02_Gradient_Descent_and_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import numpy as np

In [4]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

In [5]:
# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

In [6]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [83]:
w = torch.randn(2,3,requires_grad=True)
b = torch.randn(2,requires_grad=True)
print(w)
print(b)

tensor([[-0.0763,  1.3529, -0.5769],
        [ 1.8504,  0.5917, -0.7727]], requires_grad=True)
tensor([-0.6365, -1.1604], requires_grad=True)


In [84]:
inputs @ w.t() + b

tensor([[ 59.6297, 140.3347],
        [ 74.5518, 169.8407],
        [140.5503, 194.2936],
        [ 28.4101, 184.4301],
        [ 83.5916, 129.2305]], grad_fn=<AddBackward0>)

In [85]:
def model(x):
  return x @ w.t() + b

In [86]:
pred = model(inputs)
print(pred)

tensor([[ 59.6297, 140.3347],
        [ 74.5518, 169.8407],
        [140.5503, 194.2936],
        [ 28.4101, 184.4301],
        [ 83.5916, 129.2305]], grad_fn=<AddBackward0>)


In [87]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [88]:
diff = pred - targets

In [89]:
diff

tensor([[  3.6297,  70.3347],
        [ -6.4482,  68.8407],
        [ 21.5503,  61.2936],
        [  6.4101, 147.4301],
        [-19.4084,  10.2305]], grad_fn=<SubBackward0>)

In [90]:
diff * diff

tensor([[1.3175e+01, 4.9470e+03],
        [4.1580e+01, 4.7390e+03],
        [4.6441e+02, 3.7569e+03],
        [4.1089e+01, 2.1736e+04],
        [3.7669e+02, 1.0466e+02]], grad_fn=<MulBackward0>)

In [91]:
torch.sum(diff * diff) / diff.numel()

tensor(3622.0149, grad_fn=<DivBackward0>)

In [92]:
def mse(pred,targets):
  diff = pred - targets
  return torch.sum(diff * diff) / diff.numel()

In [93]:
loss = mse(pred,targets)
print(loss)

tensor(3622.0149, grad_fn=<DivBackward0>)


In [94]:
loss.backward()

In [95]:
print(w)
print(w.grad)

tensor([[-0.0763,  1.3529, -0.5769],
        [ 1.8504,  0.5917, -0.7727]], requires_grad=True)
tensor([[ 173.5400,  195.1815,  -25.6220],
        [6495.0513, 5261.0757, 3431.2554]])


In [96]:
print(b)
print(b.grad)

tensor([-0.6365, -1.1604], requires_grad=True)
tensor([ 1.1467, 71.6259])


In [98]:
w - w.grad * 1e-5

tensor([[-0.0780,  1.3509, -0.5767],
        [ 1.7854,  0.5391, -0.8070]], grad_fn=<SubBackward0>)

In [99]:
b - b.grad * 1e-5

tensor([-0.6365, -1.1611], grad_fn=<SubBackward0>)

In [101]:
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5

In [105]:
pred = model(inputs)

In [106]:
loss = mse(pred,targets)
print(loss)

tensor(2876.8008, grad_fn=<DivBackward0>)


In [107]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [108]:
print(w)
print(b)

tensor([[-0.0780,  1.3509, -0.5767],
        [ 1.7854,  0.5391, -0.8070]], requires_grad=True)
tensor([-0.6365, -1.1611], requires_grad=True)


In [116]:
for i in range(500):
  preds = model(inputs)
  loss = mse(preds,targets)
  print(loss)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

tensor(132.8472, grad_fn=<DivBackward0>)
tensor(132.5268, grad_fn=<DivBackward0>)
tensor(132.2078, grad_fn=<DivBackward0>)
tensor(131.8904, grad_fn=<DivBackward0>)
tensor(131.5744, grad_fn=<DivBackward0>)
tensor(131.2599, grad_fn=<DivBackward0>)
tensor(130.9469, grad_fn=<DivBackward0>)
tensor(130.6354, grad_fn=<DivBackward0>)
tensor(130.3253, grad_fn=<DivBackward0>)
tensor(130.0166, grad_fn=<DivBackward0>)
tensor(129.7093, grad_fn=<DivBackward0>)
tensor(129.4035, grad_fn=<DivBackward0>)
tensor(129.0990, grad_fn=<DivBackward0>)
tensor(128.7960, grad_fn=<DivBackward0>)
tensor(128.4941, grad_fn=<DivBackward0>)
tensor(128.1939, grad_fn=<DivBackward0>)
tensor(127.8948, grad_fn=<DivBackward0>)
tensor(127.5971, grad_fn=<DivBackward0>)
tensor(127.3006, grad_fn=<DivBackward0>)
tensor(127.0056, grad_fn=<DivBackward0>)
tensor(126.7118, grad_fn=<DivBackward0>)
tensor(126.4192, grad_fn=<DivBackward0>)
tensor(126.1279, grad_fn=<DivBackward0>)
tensor(125.8379, grad_fn=<DivBackward0>)
tensor(125.5491,

In [117]:
print(loss)

tensor(106.7668, grad_fn=<DivBackward0>)


In [118]:
print(pred)
print(targets)

tensor([[ 59.3833, 130.5922],
        [ 74.2385, 157.1038],
        [140.1526, 179.6023],
        [ 28.1586, 174.2726],
        [ 83.3024, 117.2957]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


Build-In functions

In [119]:
import torch.nn as nn

In [120]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

In [121]:
# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

In [122]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)


In [123]:
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [125]:
from torch.utils.data import TensorDataset

In [126]:
train_ds = TensorDataset(inputs,targets)

In [127]:
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [128]:
from torch.utils.data import DataLoader

In [129]:
batch_size = 2
train_dl = DataLoader(train_ds,batch_size,shuffle=True)

In [131]:
for xb , yb in train_dl:
  print(xb)
  print(yb)
  break

tensor([[ 73.,  67.,  43.],
        [ 87., 134.,  58.]])
tensor([[ 56.,  70.],
        [119., 133.]])


In [132]:
model = nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.0804, -0.2912, -0.3322],
        [-0.5504, -0.5554, -0.1384]], requires_grad=True)
Parameter containing:
tensor([0.2011, 0.4406], requires_grad=True)


In [136]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.0804, -0.2912, -0.3322],
         [-0.5504, -0.5554, -0.1384]], requires_grad=True),
 Parameter containing:
 tensor([0.2011, 0.4406], requires_grad=True)]

In [137]:
pred = model(inputs)
print(pred)

tensor([[ -39.4646,  -82.9048],
        [ -54.0039, -107.3829],
        [ -65.0829, -129.8981],
        [ -32.8149,  -84.7078],
        [ -56.5577, -100.5469]], grad_fn=<AddmmBackward0>)


In [138]:
import torch.nn.functional as F

In [139]:
loss_fn = F.mse_loss

In [140]:
loss = loss_fn(pred,targets)
print(loss)

tensor(28862.1758, grad_fn=<MseLossBackward0>)


In [141]:
opt = torch.optim.SGD(model.parameters(),lr=1e-5)

In [142]:
def fit(num_epochs,model,loss_fn,opy,train_dl):
  for epoch in range(num_epochs):
    for xb,yb in train_dl:
      pred = model(xb)
      loss = loss_fn(pred,yb)
      loss.backward()
      opt.step()
      opt.zero_grad()
    if (epoch+1) % 10 == 0:
      print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))


In [143]:
fit(100,model,loss_fn,opt,train_dl)

Epoch [10/100], Loss: 424.4935
Epoch [20/100], Loss: 121.4666
Epoch [30/100], Loss: 25.7584
Epoch [40/100], Loss: 55.0089
Epoch [50/100], Loss: 11.4125
Epoch [60/100], Loss: 122.6549
Epoch [70/100], Loss: 122.7326
Epoch [80/100], Loss: 107.9048
Epoch [90/100], Loss: 1.3316
Epoch [100/100], Loss: 74.2901


In [144]:
pred = model(inputs)
print(pred)

tensor([[ 59.6002,  71.9675],
        [ 81.3186,  99.8698],
        [122.3561, 135.2352],
        [ 30.3704,  43.5477],
        [ 94.5921, 113.7956]], grad_fn=<AddmmBackward0>)


In [145]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [147]:
model(torch.tensor([[75,63,44.]]))

tensor([[55.8498, 68.9316]], grad_fn=<AddmmBackward0>)