<a href="https://colab.research.google.com/github/PlanetDestroyyer/Pytorch-Tutorial/blob/main/Intro_to_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
print(torch.__version__)

2.5.1+cu121


In [3]:
if torch.cuda.is_available():
  print('GPU is available')
  print(torch.cuda.get_device_name(0))
else:
  print('GPU is not available')

GPU is available
Tesla T4


Creating A Tensor

In [8]:
a = torch.empty(2,3)

In [9]:
type(a)

torch.Tensor

In [10]:
torch.rand(2,3)

tensor([[0.6412, 0.6533, 0.7053],
        [0.1723, 0.5631, 0.4757]])

In [11]:
torch.rand(2,3)

tensor([[0.2402, 0.0258, 0.1302],
        [0.4807, 0.1496, 0.7562]])

In [12]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [14]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [16]:
a = torch.tensor([1,23])

In [17]:
type(a)

torch.Tensor

In [19]:
torch.range(0,10,2)

<ipython-input-19-e2293d9db2d9>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10,2)


tensor([ 0.,  2.,  4.,  6.,  8., 10.])

In [20]:
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [21]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [22]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [23]:
torch.full((3,3),7)

tensor([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]])

Tensor Shapes

In [27]:
x = torch.tensor(([1,3,5],[5,4,7]))
x

tensor([[1, 3, 5],
        [5, 4, 7]])

In [28]:
print(x.shape)

torch.Size([2, 3])


In [29]:
torch.empty_like(x)

tensor([[7309453675965983778, 8315168162784306286, 8367752027310484831],
        [7954801838398993778, 2459029315949324647, 7364850173110138466]])

In [31]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [32]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [34]:
torch.rand_like(x)

TypeError: 'torch.dtype' object is not callable

In [35]:
x.dtype

torch.int64

In [39]:
torch.rand_like(x,dtype=torch.float64)

tensor([[0.6941, 0.3464, 0.9751],
        [0.7911, 0.4274, 0.4460]], dtype=torch.float64)

In [40]:
x

tensor([[1, 3, 5],
        [5, 4, 7]])

In [41]:
x.to(torch.float64)

tensor([[1., 3., 5.],
        [5., 4., 7.]], dtype=torch.float64)

Operations

In [43]:
x + 1

tensor([[2, 4, 6],
        [6, 5, 8]])

In [44]:
x - 1

tensor([[0, 2, 4],
        [4, 3, 6]])

In [45]:
x * 2

tensor([[ 2,  6, 10],
        [10,  8, 14]])

In [46]:
x / 5

tensor([[0.2000, 0.6000, 1.0000],
        [1.0000, 0.8000, 1.4000]])

In [47]:
x // 2

tensor([[0, 1, 2],
        [2, 2, 3]])

In [48]:
x ** 2

tensor([[ 1,  9, 25],
        [25, 16, 49]])

In [78]:
a = torch.rand(2,3)
b = torch.rand(2,3)

In [50]:
a

tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])

In [51]:
b

tensor([[0.5277, 0.2472, 0.7909],
        [0.4235, 0.0169, 0.2209]])

In [52]:
a + b

tensor([[0.9717, 1.1950, 1.5354],
        [0.9127, 0.2595, 0.9212]])

In [53]:
a - b

tensor([[-0.0837,  0.7007, -0.0464],
        [ 0.0657,  0.2257,  0.4794]])

In [54]:
a * b

tensor([[0.2343, 0.2343, 0.5888],
        [0.2072, 0.0041, 0.1547]])

In [55]:
a / b

tensor([[ 0.8415,  3.8346,  0.9413],
        [ 1.1552, 14.3533,  3.1705]])

In [56]:
a // b

tensor([[ 0.,  3.,  0.],
        [ 1., 14.,  3.]])

In [57]:
a ** b

tensor([[0.6515, 0.9868, 0.7919],
        [0.7388, 0.9763, 0.9243]])

In [58]:
torch.abs(a)

tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])

In [59]:
torch.neg(a)

tensor([[-0.4440, -0.9478, -0.7445],
        [-0.4892, -0.2426, -0.7003]])

In [60]:
torch.round(a)

tensor([[0., 1., 1.],
        [0., 0., 1.]])

In [61]:
torch.ceil(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [62]:
torch.floor(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [63]:
torch.clamp(a , min=1, max=2)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [64]:
c = torch.rand(2,3)

In [66]:
c

tensor([[0.9535, 0.7064, 0.1629],
        [0.8902, 0.5163, 0.0359]])

In [65]:
torch.sum(c)

tensor(3.2652)

In [67]:
torch.mean(c)

tensor(0.5442)

In [68]:
torch.max(c)

tensor(0.9535)

In [70]:
torch.min(c)

tensor(0.0359)

In [71]:
torch.prod(c)

tensor(0.0018)

In [72]:
torch.std(c)

tensor(0.3790)

In [73]:
torch.var(c)

tensor(0.1436)

In [74]:
torch.argmax(c)

tensor(0)

In [76]:
torch.argmin(c)

tensor(5)

In [81]:
torch.sigmoid(c)

tensor([[0.7218, 0.6696, 0.5406],
        [0.7089, 0.6263, 0.5090]])

In [82]:
torch.softmax(c,dim=1)

tensor([[0.4475, 0.3495, 0.2030],
        [0.4731, 0.3255, 0.2014]])

In [83]:
torch.relu(c)

tensor([[0.9535, 0.7064, 0.1629],
        [0.8902, 0.5163, 0.0359]])

In [84]:
a.add_(b)

tensor([[1.5527, 0.9419, 0.7632],
        [1.2539, 0.5009, 0.8512]])

In [85]:
a

tensor([[1.5527, 0.9419, 0.7632],
        [1.2539, 0.5009, 0.8512]])

In [86]:
b

tensor([[0.9051, 0.5989, 0.4450],
        [0.7278, 0.4563, 0.3389]])

Tensor Operation on GPU

In [4]:
torch.cuda.is_available()

True

In [5]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [6]:
print(device)

cuda


In [7]:
a  = torch.empty(2,3)

In [8]:
a

tensor([[-8.5456e-04,  4.5443e-41, -1.3088e-23],
        [ 4.5444e-41, -8.6203e-04,  4.5443e-41]])

In [9]:
b = a.to(device)

In [10]:
b

tensor([[-8.5456e-04,  4.5443e-41, -1.3088e-23],
        [ 4.5444e-41, -8.6203e-04,  4.5443e-41]], device='cuda:0')

Reshaping of Tensor

In [11]:
a = torch.ones(2,3)

In [12]:
a

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [13]:
a.reshape(3,2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [15]:
a.reshape(6,1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]])

In [16]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1.])