<a href="https://colab.research.google.com/github/PlanetDestroyyer/Pytorch-Tutorial/blob/main/Tensor_in_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
t1 = torch.tensor([2,3])

In [ ]:
print(t1)

tensor([2, 3])


In [ ]:
t2 = torch.empty([2,3])

In [ ]:
print(t2)

tensor([[-7.8551e+13,  4.4814e-41, -7.8591e+13],
        [ 4.4814e-41,  1.5123e-38,  0.0000e+00]])


In [ ]:
t3 = torch.rand([2,1])

In [ ]:
print(t3)

tensor([[0.3439],
        [0.7635]])


In [ ]:
t4 = torch.zeros([2,3])

In [ ]:
print(t4)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
t5 = torch.ones([2,2])

In [ ]:
print(t5)

tensor([[1., 1.],
        [1., 1.]])


In [ ]:
print(t5.dtype)

torch.float32


In [ ]:
t5 = torch.ones([2,2],dtype=torch.int8)

In [ ]:
print(t5)

tensor([[1, 1],
        [1, 1]], dtype=torch.int8)


In [ ]:
t6 = torch.tensor([5,2,3,2,2],dtype=torch.float16)

In [ ]:
print(t6)

tensor([5., 2., 3., 2., 2.], dtype=torch.float16)


In [ ]:
x = torch.rand([2,2])
y = torch.rand([2,2])

In [ ]:
print(x)

tensor([[0.0894, 0.5156],
        [0.2113, 0.4769]])


In [ ]:
print(y)

tensor([[0.8453, 0.4308],
        [0.6774, 0.9906]])


In [ ]:
print(x+y)

tensor([[0.6302, 1.1063],
        [0.6528, 0.7753]])


In [ ]:
print(x-y)

tensor([[ 0.3234,  0.5229],
        [-0.4785, -0.1070]])


In [ ]:
print(x*y)

tensor([[0.0731, 0.2376],
        [0.0493, 0.1474]])


In [ ]:
print(x%y)

tensor([[0.0166, 0.2311],
        [0.0872, 0.3341]])


In [ ]:
print(x/y)

tensor([[3.1083, 2.7923],
        [0.1541, 0.7574]])


In [ ]:
print(y)

tensor([[0.8453, 0.4308],
        [0.6774, 0.9906]])


In [ ]:
y.add_(x)

tensor([[0.9347, 0.9463],
        [0.8888, 1.4675]])

In [ ]:
print(y)

tensor([[0.9347, 0.9463],
        [0.8888, 1.4675]])


In [ ]:
t7 = torch.rand([3,4])

In [ ]:
print(t7)

tensor([[0.8048, 0.3339, 0.4044, 0.7063],
        [0.9461, 0.6021, 0.5654, 0.3751],
        [0.9450, 0.9725, 0.9003, 0.8106]])


In [ ]:
print(t7[1,1])

tensor(0.6021)


In [ ]:
print(t7[1,1].item())

0.6021079421043396


NUMPY TO PYTORCH

In [ ]:
import numpy as np

In [ ]:
t1 = torch.rand([2,2])

In [ ]:
print(type(t1))

<class 'torch.Tensor'>


In [ ]:
t2 = t1.numpy()

In [ ]:
print(type(t2))

<class 'numpy.ndarray'>


In [ ]:
t1 = np.ones(5)

In [ ]:
print(t1)

[1. 1. 1. 1. 1.]


In [ ]:
t2 = torch.tensor(t1)

In [ ]:
print(t2)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
